### ISSUE TITLE
Unable to sync in china

### ISSUE THREAD

**Issue by tygk5211314** [teamswipp/swippcore#9] opened 2018-05-26 01:41 UTC
Unable to sync in china.

在中国无法同步

**Comment by teamswipp** [comment] 2018-05-27 06:55
Please use English, I have edited your report to include it.

This is not a bug in Swipp. We will not add code to circumvent the Chinese firewall. If you have problems in China, use a proxy and/or tor or some encrypted tunnel - this is what most people do to get around it.

If you give me some details I might be able to see what the problem is.

Can you ping "node1.swippcoin.com" ?
If not, what happens if you do a traceroute to "node1.swippcoin.com" ?

**Comment by teamswipp** [comment] 2018-07-11 21:28
Not a Swipp issue, so closing.

**Closed as completed by teamswipp** 2018-07-11 21:28 UTC
Labels: invalid
